{{- if .Values.local.minio.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ $.Release.Namespace }}
annotations:
  "helm.sh/hook": pre-install
  "helm.sh/hook-weight": "-5"
data:
  rootUser: dmFsdWUtMg0KDQo=
  rootPassword: dmFsdWUtMg0KDQo=
{{- end }}
