apiVersion: v2
name: meta-monitoring
description: A Helm chart for meta monitoring Grafana Loki, Mimir and Tempo
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.3.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
dependencies:
- name: loki
  repository: https://grafana.github.io/helm-charts
  version: 6.29.0
  condition: local.logs.enabled
- name: alloy
  repository: https://grafana.github.io/helm-charts
  version: 1.0.2
- name: mimir-distributed
  repository: https://grafana.github.io/helm-charts
  version: 5.7.0
  condition: local.metrics.enabled
- name: tempo-distributed
  repository: https://grafana.github.io/helm-charts
  version: 1.38.2
  condition: local.traces.enabled
- name: minio
  repository: https://charts.min.io
  version: 5.4.0
  condition: local.minio.enabled
